insert into USERS ( LOGIN, EMAIL, FIRST_NAME, LAST_NAME) values ('LOGIN1','EMAIL1','NAME1','LASTNAME1');
insert into USERS ( LOGIN, EMAIL, FIRST_NAME, LAST_NAME) values ('LOGIN2','EMAIL2','NAME2','LASTNAME2');
insert into USERS ( LOGIN, EMAIL, FIRST_NAME, LAST_NAME) values ('LOGIN3','EMAIL3','NAME3','LASTNAME3');
insert into USERS ( LOGIN, EMAIL, FIRST_NAME, LAST_NAME) values ('LOGIN4','EMAIL4','NAME4','LASTNAME4');
insert into USERS ( LOGIN, EMAIL, FIRST_NAME, LAST_NAME) values ('LOGIN5','EMAIL5','NAME5','LASTNAME5');
